# Generated by Django 5.2.3 on 2025-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Review_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_photo', models.ImageField(upload_to='book_photos/')),
                ('book_url', models.URLField(blank=True)),
                ('book_review', models.CharField(max_length=500)),
            ],
        ),
    ]
