# Generated by Django 5.2.3 on 2025-09-07 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_book_review_forms_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review_forms',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
