# Generated by Django 5.2.3 on 2025-12-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0005_book_category_book_review_forms_book_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_review_forms',
            name='book_name',
        ),
    ]
